In [71]:
import numpy as np

In [72]:
from array import array

In [200]:
from random import random

In [45]:
floats = array('d',(random() for i in range(10 ** 8)))

In [50]:
floats[:3]

array('d', [0.6286678736429907, 0.6985740264037922, 0.3876888425568562])

In [51]:
haystack = dict.fromkeys(floats)

In [74]:
import pandas as pd

In [133]:
idx = pd.MultiIndex.from_tuples([('red','one'),('red','two'),('blue','three')])

In [142]:
idx.names = ['A','B']

In [182]:
idx

MultiIndex([( 'red',   'one'),
            ( 'red',   'two'),
            ('blue', 'three')],
           names=['A', 'B'])

In [183]:
df = pd.DataFrame({'a':[-2,-1,1,10,8,11,-1],'b':list('abcdeff'),'c': [1.0,2.0,4.0,3.2,np.nan,3.0,4.0]},index=['a','b','c','d','e','f','g'])

In [184]:
df

a  b    c
a  -2  a  1.0
b  -1  b  2.0
c   1  c  4.0
d  10  d  3.2
e   8  e  NaN
f  11  f  3.0
g  -1  f  4.0

In [185]:
df.reindex(['b','d','c','a','e','g','f'])

a  b    c
b  -1  b  2.0
d  10  d  3.2
c   1  c  4.0
a  -2  a  1.0
e   8  e  NaN
g  -1  f  4.0
f  11  f  3.0

In [186]:
df.sort_values(by='a')

a  b    c
a  -2  a  1.0
b  -1  b  2.0
g  -1  f  4.0
c   1  c  4.0
e   8  e  NaN
d  10  d  3.2
f  11  f  3.0

In [187]:
idx = pd.MultiIndex.from_tuples([('a',1),('a',2),('a',2),('b',2),('b',1),('b',1)])

In [188]:
idx.names = ['first','second']

In [189]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 2),
            ('b', 2),
            ('b', 1),
            ('b', 1)],
           names=['first', 'second'])

In [193]:
df = pd.DataFrame({'A':np.arange(6,0,-1)},index=idx)

In [194]:
df

A
first second   
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

In [195]:
d = {'a':1,'b':2,'c':3,'d':4,'e':5}

In [197]:
d = dict([('a',1),('b',2),('c',3),('d',4),('e',5)])

In [210]:
d = dict.fromkeys((x for x in range(5)),'my')

In [211]:
d

{0: 'my', 1: 'my', 2: 'my', 3: 'my', 4: 'my'}

In [179]:
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [181]:
print(arr2[0])

[0 1 2]


In [230]:
print(s1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [231]:
# 集合  字典

TypeError: unhashable type: 'list'

False

In [229]:
a

{(1, 2, 3), 2}